name: BD SCA Security Action Full Scan Gate

on:
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  security-scan:
    name: Black Duck SCA FULL Scan
    #GitHub에서 관리하는 최신 Ubuntu 환경 사용
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            bzip2 \
            wget

      - name: Verify BusyBox Version
        run: |
          grep '^VERSION =' Makefile
          grep '^PATCHLEVEL =' Makefile

      - name: Configure BusyBox
        run: |
          make distclean
          make allnoconfig

      - name: Build BusyBox
        run: |
          make

      - name: Verify Binary
        run: |
          file busybox
          ./busybox --help | head -20

      #- name: Upload Artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: busybox-binary
      #    path: busybox

      # Black Duck SCA 실행 및 보안 게이트 적용
      - name: Run Black Duck SCA Full Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # Full Scan(Intelligent Mode) 강제 설정
         # detect_args: '--detect.blackduck.scan.mode=INTELLIGENT'

          detect_args: |
            --detect.blackduck.scan.mode=INTELLIGENT
            --detect.project.name=busybox-1.31-demo
            --detect.project.version.name=1.0
           

          # --detect.diagnostic=true
          # --logging.level.detect=DEBUG
          # 스캔 완료 후 결과가 서버에 반영될  때까지 대기하여 Policy check (게이트 판정에 필수)
          blackducksca_waitForScan: 'true'
          
          # ⭐ 핵심: 지정한 심각도 이상의 취약점 발견 시 빌드 실패(FAIL) 처리
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          # PR 화면에 취약점 요약 코멘트 자동 작성
          # PrCommand -> rapid scan 만 지원 Koishi 페이지에서도:
          # Full Black Duck scan is not supported for Pull Request comment in Github Actions Integration.
          #blackducksca_prComment_enabled: 'true'
          
          # (선택) 취약점 수정 PR 자동 생성
          #blackducksca_fixpr_enabled: 'true'
          
          #GitHub Code Scanning(GHAS)  업로드를 원할 경우
          blackducksca_reports_sarif_create: 'true'

          #
          blackducksca_upload_sarif_report: 'true' 
          
      - name: Show Bridge files 
        if: always() 
        run: | 
          pwd 
          find .bridge -type f | sort
